import { Link, useNavigate, useParams } from "react-router";
import { useEffect, useState } from "react";
import { usePuterStore } from "~/lib/puter";
import Navbar from "~/components/Navbar";
import Summary from "~/components/Summary";
import ATS from "~/components/ATS";
import Details from "~/components/Details";

export const meta = () => ([
    { title: 'Resumind | Review ' },
    { name: 'description', content: 'Detailed overview of your resume' },
])

const Resume = () => {
    const { auth, isLoading, fs, kv } = usePuterStore();
    const { id } = useParams();
    const [imageUrl, setImageUrl] = useState('');
    const [resumeUrl, setResumeUrl] = useState('');
    const [feedback, setFeedback] = useState<Feedback | null>(null);
    const navigate = useNavigate();

    useEffect(() => {
        if (!isLoading && !auth.isAuthenticated) navigate(`/auth?next=/resume/${id}`);
    }, [isLoading, auth.isAuthenticated, navigate, id])

    useEffect(() => {
        const loadResume = async () => {
            const resume = await kv.get(`resume:${id}`);

            if (!resume) return;

            const data = JSON.parse(resume);

            const resumeBlob = await fs.read(data.resumePath);
            if (!resumeBlob) return;

            const pdfBlob = new Blob([resumeBlob], { type: 'application/pdf' });
            const resumeUrl = URL.createObjectURL(pdfBlob);
            setResumeUrl(resumeUrl);

            const imageBlob = await fs.read(data.imagePath);
            if (!imageBlob) return;
            const imageUrl = URL.createObjectURL(imageBlob);
            setImageUrl(imageUrl);

            setFeedback(data.feedback);
        }

        loadResume();
    }, [id]);

    return (
        <div className="min-h-screen bg-slate-50 flex flex-col">
            <Navbar />

            <main className="flex-1 w-full max-w-[1600px] mx-auto px-4 sm:px-6 lg:px-8 py-8">
                <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 h-[calc(100vh-8rem)] min-h-[600px]">
                    {/* Resume Preview Column - Sticky on Desktop */}
                    <div className="lg:col-span-5 h-full flex flex-col">
                        <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden flex flex-col h-full sticky top-4">
                            <div className="p-4 border-b border-slate-200 flex justify-between items-center bg-slate-50">
                                <h2 className="font-semibold text-slate-700">Resume Preview</h2>
                                {resumeUrl && (
                                    <a href={resumeUrl} target="_blank" rel="noopener noreferrer" className="text-brand-600 hover:text-brand-700 text-sm font-medium">
                                        Open PDF ↗
                                    </a>
                                )}
                            </div>
                            <div className="flex-1 overflow-auto bg-slate-200 p-4 flex items-start justify-center">
                                {imageUrl ? (
                                    <img
                                        src={imageUrl}
                                        className="w-full max-w-full shadow-lg rounded-sm"
                                        alt="resume preview"
                                    />
                                ) : (
                                    <div className="flex items-center justify-center h-full text-slate-400">
                                        Loading preview...
                                    </div>
                                )}
                            </div>
                        </div>
                    </div>

                    {/* Analysis Column - Scrollable */}
                    <div className="lg:col-span-7 h-full overflow-y-auto pr-2 custom-scrollbar">
                        <div className="space-y-6">
                            <div className="flex items-center justify-between">
                                <h1 className="text-2xl font-bold text-slate-900">Analysis Results</h1>
                                <span className="text-sm text-slate-500">Generated by AI</span>
                            </div>

                            {feedback ? (
                                <>
                                    <Summary feedback={feedback} />
                                    <ATS score={feedback.ATS.score || 0} suggestions={feedback.ATS.tips || []} />
                                    <Details feedback={feedback} />
                                </>
                            ) : (
                                <div className="card p-12 flex flex-col items-center justify-center text-center space-y-4">
                                    <div className="w-16 h-16 border-4 border-slate-200 border-t-brand-600 rounded-full animate-spin"></div>
                                    <p className="text-lg font-medium text-slate-900">Analyzing your resume...</p>
                                    <p className="text-slate-500 max-w-sm">This usually takes about 10-20 seconds. We're checking against ATS standards and job requirements.</p>
                                </div>
                            )}
                        </div>
                    </div>
                </div>
            </main>
        </div>
    )
}
export default Resume
